---
name: Build Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    tags:
      - v*

jobs:
  build:
    name: Build Pipeline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup binaries. Poetry, Twine.
        run: make setup-binaries

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: poetry

      - name: Install dependencies
        run: make install

      - name: Lint code
        run: make lint

      - name: Run tests
        run: make test

      - name: Build package
        run: make build

      - name: Publish package to PyPI
        if: startsWith(github.ref, 'refs/tags')
        run: |
          poetry config pypi-token.pypi "${{ secrets.PYPI_API_TOKEN }}"
          make publish
